# Generated by Django 3.2.11 on 2023-04-16 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot_server', '0002_datavalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='local',
            field=models.BooleanField(default=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
