# Generated by Django 3.2.11 on 2023-04-22 17:37

import apps.iot_server.models
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iot_server', '0003_auto_20230416_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='_token_data',
            field=encrypted_fields.fields.EncryptedCharField(default=apps.iot_server.models.init_api_token_str, max_length=512),
        ),
        migrations.AddField(
            model_name='datasource',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='token',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_token_data', hash_key='caf78fb43483e5e63439dc8ecc9d44669aa5cd87b1df8cbea262c969defcc7ee', max_length=66, null=True),
        ),
    ]
